- DevOps:
    - Kubernetes Docs:
        - href: https://kubernetes.io/docs/
    - Helm Docs:
        - href: https://helm.sh/docs/
    - Grafana Docs:
        - href: https://grafana.com/docs/

- Projet Annuel:
    - GitHub:
        - href: https://github.com/Kadem9/curateur-esgi-projet
