{{- if and .Values.github.enabled .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homepage.fullname" . }}-github-token
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
type: Opaque
stringData:
  HOMEPAGE_VAR_GITHUB_TOKEN: {{ .Values.github.token | quote }}
{{- end }}
