{{- if and .Values.trello.enabled .Values.trello.key .Values.trello.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homepage.fullname" . }}-trello
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
type: Opaque
stringData:
  HOMEPAGE_VAR_TRELLO_KEY: {{ .Values.trello.key | quote }}
  HOMEPAGE_VAR_TRELLO_TOKEN: {{ .Values.trello.token | quote }}
{{- end }}
