apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
type: Opaque
stringData:
  HOMEPAGE_ALLOWED_HOSTS: {{ .Values.secret.allowedHosts | quote }}
