apiVersion: v1
kind: Secret
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
type: Opaque
stringData:
  HOMEPAGE_ALLOWED_HOSTS: homepage.local,localhost,127.0.0.1